import KnawatMP from './KnawatMP';
import categories from './api/categories';
import coupons from './api/coupons';
import invoices from './api/invoices';
import membership from './api/memberships';
import miscellaneous from './api/miscellaneous';
import orders from './api/orders';
import payments from './api/payments';
import products from './api/products';
import myProducts from './api/my-products';
import shipping from './api/shipping';
import stores from './api/stores';
import subscriptions from './api/subscriptions';
import taxes from './api/taxes';
import logs from './api/logs';

KnawatMP._addToPrototype(categories);
KnawatMP._addToPrototype(coupons);
KnawatMP._addToPrototype(invoices);
KnawatMP._addToPrototype(membership);
KnawatMP._addToPrototype(miscellaneous);
KnawatMP._addToPrototype(orders);
KnawatMP._addToPrototype(payments);
KnawatMP._addToPrototype(products);
KnawatMP._addToPrototype(myProducts);
KnawatMP._addToPrototype(shipping);
KnawatMP._addToPrototype(stores);
KnawatMP._addToPrototype(subscriptions);
KnawatMP._addToPrototype(taxes);
KnawatMP._addToPrototype(logs);

module.exports = KnawatMP;
